Vagrant.configure("2") do |config|
  config.vm.network "private_network", type: "dhcp"

  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true

  config.hostmanager.ip_resolver = proc do |vm, resolving_vm|
    if hostname = (vm.ssh_info && vm.ssh_info[:host])
      # vm にアクセスするための IP アドレスには enp0s8 のものを使用する
      vm.communicate.execute("ip -4 a show dev enp0s8 | grep inet | awk '{print $2}' | cut -f 1 -d /") do |type, contents|
        break contents.strip
      end
    end
  end

  # service 仮想マシン
  config.vm.define "service" do |service|
    service.vm.box = "ubuntu/jammy64"
    service.vm.hostname = "service"
    service.vm.network "forwarded_port", guest: 80, host: 8080
    
    service.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nginx

      # Nginx のレスポンスを設定
      echo "The service is available!" > /var/www/html/index.nginx-debian.html

      # TCP SYN Cookies を無効化する
      echo 0 > /proc/sys/net/ipv4/tcp_syncookies
      sysctl -w net.ipv4.tcp_syncookies=0
      echo "net.ipv4.tcp_syncookies = 0" >> /etc/sysctl.conf
      
      systemctl start nginx
    SHELL
  end

  # attacker 仮想マシン
  config.vm.define "attacker" do |attacker|
    attacker.vm.box = "ubuntu/jammy64"
    attacker.vm.hostname = "attacker"

    # hping3のインストール
    attacker.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y hping3

      # 80 番ポートへの outgoing な RST パケットを破棄する
      sudo iptables -A OUTPUT -p tcp --dport 80 --tcp-flags RST RST -j DROP
    SHELL
  end
end

